project:
  base_model: meta-llama/Llama-3.2-3B
  project_name: latest-second-price-p
  username: ujalaarshad17

dataset:
  user: ed-donner
  name: items_prompts_lite
  val_size: 500

training:
  epochs: 4
  batch_size: 128
  max_sequence_length: 148
  gradient_accumulation_steps: 1
  learning_rate: 5e-4
  warmup_ratio: 0.05
  lr_scheduler_type: cosine
  weight_decay: 0.001
  optimizer: paged_adamw_32bit
  log_steps: 5
  save_steps: 100

lora:
  r: 64
  dropout: 0.2
  target_modules: [q_proj, v_proj, k_proj, o_proj]

quantization:
  use_4bit: false

logging:
  use_wandb: true
